workflow

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -23,8 +23,6 @@ jobs:
     - name: Run Python scripts
       run: |
         for file in $(find . -type f -name '*.py'); do
-          if [ -f "$file" ]; then
-            echo "Running $file"
-            python "$file" || { echo "$file failed"; exit 1; }
-          fi
+          echo "Running $file"
+          python "$file" || { echo "$file failed"; exit 1; }
         done
